#!/usr/bin/env bash

set -e

root_dir=$(cd $(dirname $0); echo $(pwd))

#cd *-web

npm install
bower install

#cd "$root_dir"

mvn -Ptest install eclipse:eclipse

rm -rf */.settings/

# mvn compile war:war -pl *-web
