#!/usr/bin/env bash

set -e

mvn -Ptest jetty:run -pl *-web \
  -Dfactories.dao=poo.library.dao.jpa.MySqlConnectionDAOFactory

# mvn -Ptest jetty:run -pl *-web \
#   -Dfactories.dao=poo.library.dao.jpa.PostgreSqlConnectionDAOFactory
